name: Pipeline

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: xdebug, pdo_sqlsrv, sqlsrv

      - name: Make Environment Variables in .env
        run: |
          echo "APP_NAME=ContaDigitalDinariFront" >> .env
          echo "APP_ENV=local" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_PORT=8000" >> .env
          echo "APP_URL=http://localhost:8000" >> .env
          echo "ENDPOINT_TO_BACK=http://localhost:8001/api/" >> .env
          echo "LOG_CHANNEL=stack" >> .env
          echo "LOG_LEVEL=debug" >> .env
          echo "GOOGLE_RECAPTCHA_KEY=6Lei3ekUAAAAAEGpq-8PD7_5FF1i69cJmg04qFwG" >> .env
          echo "SAIL_XDEBUG_MODE=develop,debug" >> .env
          echo "SAIL_XDEBUG_CONFIG='start_with_request=yes client_host=host.docker.internal idekey=VSCODE log_level=0'" >> .env
          echo "WWWUSER=1000" >> .env
          echo "WWWGROUP=1000" >> .env
          echo "THREAT_METRIX_ORG_ID=" >> .env
          echo "DB_CONNECTION=sqlsrv" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=1433" >> .env
          echo "DB_DATABASE=test_db" >> .env
          echo "DB_USERNAME=sa" >> .env
          echo "DB_PASSWORD=your_password_here" >> .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run SQL Server in Docker
        run: |
          docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=your_password_here' -p 1433:1433 --name sqlserver -d mcr.microsoft.com/mssql/server:2022-latest

      - name: Wait for SQL Server to be ready
        run: |
          while ! docker exec sqlserver /opt/mssql-tools/bin/sqlcmd -U sa -P your_password_here -Q "SELECT 1" > /dev/null 2>&1; do
            echo "Aguardando SQL Server iniciar..."
            sleep 5
          done
          echo "SQL Server iniciado!"

      - name: Create Database
        run: |
          docker exec sqlserver /opt/mssql-tools/bin/sqlcmd -U sa -P your_password_here -Q "CREATE DATABASE test_db"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run migration
        run: php artisan migrate:fresh --seed
        
      - name: Run PHPUnit tests with coverage
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=junit.xml

      # Extrair cobertura do arquivo coverage.xml
      - name: Extract coverage
        id: coverage_check
        run: |
          COVERAGE=$(php -r "
              libxml_use_internal_errors(true);
              \$xml = simplexml_load_file('coverage.xml');
              if (\$xml === false) {
                  echo 'Erro ao carregar o arquivo coverage.xml';
                  exit(1);
              }
              \$coverage = (\$xml->project->metrics['coveredelements'] / \$xml->project->metrics['elements']) * 100;
              echo round(\$coverage, 2);
          ")
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "Cobertura calculada: $COVERAGE%"

      # Parse junit.xml para obter dados adicionais
      - name: Parse junit.xml
        id: parse_junit
        run: |
          TESTS=$(php -r "
              \$xml = simplexml_load_file('junit.xml');
              echo (int) \$xml->testsuite['tests'];
          ")
          FAILURES=$(php -r "
              \$xml = simplexml_load_file('junit.xml');
              echo (int) \$xml->testsuite['failures'];
          ")
          SKIPPED=$(php -r "
              \$xml = simplexml_load_file('junit.xml');
              echo (int) \$xml->testsuite['skipped'];
          ")
          TIME=$(php -r "
              \$xml = simplexml_load_file('junit.xml');
              echo (float) \$xml->testsuite['time'];
          ")

          echo "total_tests=$TESTS" >> $GITHUB_ENV
          echo "failures=$FAILURES" >> $GITHUB_ENV
          echo "skipped=$SKIPPED" >> $GITHUB_ENV
          echo "execution_time=$TIME" >> $GITHUB_ENV

      # Comentar resultados na PR
      - name: Post test results
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### PHPUnit Test Coverage Report 

            - **Total Coverage:** ${{ env.COVERAGE }}%
            - **Total Tests:** ${{ env.total_tests }}
            - **Failures:** ${{ env.failures }}
            - **Skipped:** ${{ env.skipped }}
            - **Execution Time:** ${{ env.execution_time }} seconds

      - name: Validate test failures
        if: always() 
        run: |
          if [ ${{ env.failures }} -gt 0 ]; then
              echo "Existem falhas nos testes: ${{ env.failures }}"
              exit 1
          fi
