nome : Mesclar de volta Hotfix

sobre :
  solicitação de pull :
    tipos : [fechado]         
    galhos :
      - mestre              

liberdades :
  conteúdo : escrever
  transmissões de pull : escrever

empregos :
  mesclar novamente :
    se : ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'hotfix/') }}
    execute em : ubuntu-latest
    passos :
      - nome : Checkout do código
        usos : ações/checkout@v4

      - nome : Configurar Git
        correr : |
          git config --global user.name "Ações do GitHub"
          git config --global user.email "actions@github.com"
      - name : Criar Pull Request do master para dev
        id : criar_pr
        correr : |
          PR_URL=$(gh pr criar \
            --base dev \
            --chefe de departamento \
            --title "Mesclar de volta o hotfix para dev" \
            --body "Sincronizando as correções do master para dev.")
          PR_NUMBER=$(echo $PR_URL | grep -oE '[0-9]+$')
          eco "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          eco "PR_URL=$PR_URL" >> $GITHUB_ENV
        ambiente :
          GH_TOKEN : ${{ secrets.PAT_TOKEN }}

      - nome : Mesclar PR automaticamente (Squash)
        se : env.PR_NUMBER != ''
        correr : |
          gh pr mesclar $PR_NUMBER --squash
        ambiente :
          GH_TOKEN : ${{ secrets.PAT_TOKEN }}

      - nome : Notificar no Slack (Erro)
        se : falha()
        correr : |
          curl -X POST -H 'Tipo de conteúdo: application/json' --data '{
            "text": "Ocorreu um erro ao tentar mesclar o PR #${{ env.PR_NUMBER }} \n*Link:* ${{ env.PR_URL }}"
          }' ${{ segredos.SLACK }}
