name: Validate PHP Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: |
        composer install || echo "Nenhum composer.json encontrado, pulando."

    - name: Run PHP_CodeSniffer
      run: |
        if [ -f ./vendor/bin/phpcs ]; then
          ./vendor/bin/phpcs --standard=PSR12 src/ || echo "PHP_CodeSniffer encontrou problemas."
        else
          echo "PHP_CodeSniffer não está configurado. Pule esta etapa."
        fi

    - name: Run PHPUnit Tests
      run: |
        if [ -f ./vendor/bin/phpunit ]; then
          ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage/clover.xml || echo "Testes falharam."
        else
          echo "PHPUnit não está configurado. Pule esta etapa."
        fi

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/clover.xml

    - name: Install HTMLHint
      run: |
        npm install -g htmlhint

    - name: Run HTMLHint
      run: |
        htmlhint "**/*.html"

    - name: Install Stylelint
      run: |
        npm install -g stylelint stylelint-config-standard

    - name: Run Stylelint
      run: |
        stylelint "**/*.css" || echo "Stylelint encontrou problemas."

    - name: Install ESLint
      run: |
        npm install -g eslint

    - name: Run ESLint
      run: |
        eslint "**/*.js" || echo "ESLint encontrou problemas."

