name: Validate PHP Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
    # Clona o repositório
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configura a versão do PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # Atualize para a versão do PHP que você está usando
        tools: composer # Instala o Composer

    # Instalar o Xdebug
    - name: Install Xdebug
      run: |
        sudo apt-get install -y php-xdebug

    # Habilitar o Xdebug
    - name: Enable Xdebug
      run: |
        echo "zend_extension=$(php -r 'echo ini_get(\"extension_dir\");')/xdebug.so" | sudo tee -a /etc/php/8.3/cli/php.ini

    # Cache para dependências do Composer
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    # Verifica se o composer.json existe antes de tentar instalar dependências
    - name: Verificar se composer.json existe
      run: |
        if [ -f composer.json ]; then
          echo "composer.json encontrado, instalando dependências."
          composer install --no-ansi --prefer-dist
        else
          echo "composer.json não encontrado. Pulando instalação do Composer."
        fi

    # Verifica o padrão de código com PHP_CodeSniffer
    - name: Run PHP_CodeSniffer
      run: |
        if [ -f ./vendor/bin/phpcs ]; then
          ./vendor/bin/phpcs --standard=PSR12 . || echo "PHP_CodeSniffer encontrou problemas."
        else
          echo "PHP_CodeSniffer não está configurado. Pule esta etapa."
        fi

    # Executa os testes com PHPUnit
    - name: Run PHPUnit Tests
      run: |
        mkdir -p coverage  # Garante que o diretório de cobertura existe
        if [ -f ./vendor/bin/phpunit ]; then
          ./vendor/bin/phpunit --coverage-clover=coverage/clover.xml || echo "Testes falharam."
        else
          echo "PHPUnit não está configurado. Pule esta etapa."
        fi

    # Atualizando para a versão mais recente da ação de upload de artefatos
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/clover.xml
